# アカウント作成
POST https://api.tdu.app/user
Content-Type: application/x-www-form-urlencoded

# ユーザ名
user_name=[user name]

###
# ユーザ情報取得

GET https://api.tdu.app/user?id=[id]

###
# 名前変更
POST https://api.tdu.app/user
Content-Type: application/x-www-form-urlencoded

id=[id]&user_name=[new user name]

###
# アカウント削除
DELETE https://api.tdu.app/user?id=[id]

###
# ログ取得
GET https://api.tdu.app/log?id=[id]

###
# ログ追加
POST https://api.tdu.app/log
Content-Type: application/json

{
    "id": "[id]",
    "logs": [
        {
            // dateはRFC3339形式
            "date": "2013-09-02T01:55:20.120Z",
            "campus": "千住",
            "log_type": "1",
            "label": "",
            "code": "2000"
        }
    ]
}

###
# ランキング
GET https://api.tdu.app/rank
