name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      datastore:
        image: singularities/datastore-emulator
        env:
          DATASTORE_LISTEN_ADDRESS: 0.0.0.0:18001
          DATASTORE_PROJECT_ID: logcation
        ports:
          - 18001:18001
    env:
      DATASTORE_EMULATOR_HOST: localhost:18001
      DATASTORE_PROJECT_ID: logcation
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
